[workspace]
members = ["db", "cli"]
resolver = "2"

[workspace.dependencies]
color-eyre = "0.6.3"
sqlx = { version = "0.7", default-features = false }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.40"
