[package]
name = "db"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { workspace = true, features = [
  "postgres",
  "runtime-tokio-rustls",
  "chrono",
  "migrate",
  "macros",
  "uuid",
] }
color-eyre = { workspace = true }
tracing = { workspace = true }
uuid = { version = "1.8.0", features = ["v4"] }

[dev-dependencies]
tokio = { workspace = true }
