name: main Branch CI/CD

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    name: Tests

  deploy:
    secrets: inherit
    needs:
      - tests
    uses: ./.github/workflows/deploy.yml
    name: Deploy
